evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /

aide:
    resource: "@AideBundle/Resources/config/routing.yml"
    prefix:   /aide

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

app:
    resource: '@AppBundle/Controller/'
    type: annotation

